services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - api-gateway

  api-gateway:
    build: ./api-gateway
    ports:
      - "4000:4000"
    environment:
      # A URL é montada dinamicamente com as variáveis seguras
      - DB_URL=mysql://${MYSQL_USER}:${MYSQL_PASSWORD}@database:3306/${MYSQL_DATABASE}
      - RABBITMQ_URL=${RABBITMQ_URL}
    depends_on:
      - database
      - message-broker

  worker:
    build: ./worker
    environment:
      - RABBITMQ_URL=${RABBITMQ_URL}
    depends_on:
      - message-broker

  message-broker:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

  database:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - "3306:3306"